apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-app
  template:
    metadata:
      labels:
        app: news-app

    spec:
      containers:
        - name: news-app
          image: jp.icr.io/news-tracker-app/news-tracker-application:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
              
